name: build-readme
on: 
    push:
    pull_request:
    schedule:
      - cron: '16 0/6 * * *'
jobs:
  start-update:
    runs-on: ubuntu-latest
    env:
      OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |-
          pip install -r requirements.txt
      - name: Run Update README
        run: |-
          python update_readme.py
      - name: Commit to repo
        run: |-
          git diff
          git config --global user.email "plj611@outlook.com"
          git config --global user.name "plj611-autobot"
          git pull
          git add -A
          git commit -m "Update README" || exit 0
          git push